excel_writer.lo: /soft/php/php-excel-writer/excel_writer.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/soft/php/php-excel-writer $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /soft/php/php-excel-writer/excel_writer.c -o excel_writer.lo 
kernel/exception.lo: /soft/php/php-excel-writer/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/soft/php/php-excel-writer $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /soft/php/php-excel-writer/kernel/exception.c -o kernel/exception.lo 
kernel/excel.lo: /soft/php/php-excel-writer/kernel/excel.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/soft/php/php-excel-writer $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /soft/php/php-excel-writer/kernel/excel.c -o kernel/excel.lo 
kernel/write.lo: /soft/php/php-excel-writer/kernel/write.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/soft/php/php-excel-writer $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /soft/php/php-excel-writer/kernel/write.c -o kernel/write.lo 
$(phplibdir)/excel_writer.la: ./excel_writer.la
	$(LIBTOOL) --mode=install cp ./excel_writer.la $(phplibdir)

./excel_writer.la: $(shared_objects_excel_writer) $(EXCEL_WRITER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_excel_writer) $(EXCEL_WRITER_SHARED_LIBADD)

